algoritmo "semnome"
// Função :
// Autor :
// Data : 2/8/2019
// Seção de Declarações 
var

  n  :   inteiro
  num  : inteiro

inicio
// Seção de Comandos


         n <-2
          num <- n*1
          num <- n*2
          num <- n*3
          num <- n*4
          num <- n*5
          num <- n*6
          num <- n*7
          num <- n*8
          num <- n*9
          num <- n*10
         
     escreva("A tabuada de 2 é: ", num)
          leia(num)

fimalgoritmo
